[theme]
base="dark"
primaryColor="#e64747"
backgroundColor="#922f2f"
secondaryBackgroundColor="#771414"

[theme]
base="dark"
primaryColor="#75ffd1"
backgroundColor="#06527f"
secondaryBackgroundColor="#003f4a"